Carbon:
  IncludeAssets:
    Packages:
      'aa_Distribution':
        Package: 'Litefyr.Distribution'
        General:
          Head:
            - HeadTags.html
        Live:
          Head: HeadTagsLive.html
          BodyStart: BodyTagsLive.html
