name: 'Build Docker image'

concurrency: build

on:
  workflow_dispatch:

jobs:
  params:
    # Make environment variables available to the rest of the workflow
    name: Set environment variables
    runs-on: ubuntu-latest
    steps:
      # Get stack name from repository name
      - id: params
        name: Get parameter
        run: |
          echo "stack_name_lowercase=$(echo 'console.log("${{ github.repository }}".split(".").pop().toLowerCase())' | node -)" >> $GITHUB_OUTPUT
          echo "repository_owner_lowercase=$(echo 'console.log("${{ github.repository_owner }}".toLowerCase())' | node -)" >> $GITHUB_OUTPUT
    outputs:
      stack_name_lowercase: ${{ steps.params.outputs.stack_name_lowercase }}
      repository_owner_lowercase: ${{ steps.params.outputs.repository_owner_lowercase }}

  build:
    name: Build files
    uses: Litefyr/Workflows/.github/workflows/build.yaml@main
    secrets:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

  docker:
    name: Build Neos docker image
    needs:
      - params
      - build
    uses: Litefyr/Workflows/.github/workflows/docker.yaml@main
    with:
      tags: ghcr.io/${{ needs.params.outputs.repository_owner_lowercase }}/litefyr-${{ needs.params.outputs.stack_name_lowercase }}/neos:latest
